#!/usr/bin/env python3
import os
import re
import logging
import requests
import datetime
from slickrpc import Proxy
from os.path import expanduser
from dotenv import load_dotenv
from logging import Handler, Formatter

# DEPS:
# sudo apt-get install libgnutls28-dev python3 python3-pip python3-setuptools python3-six
# pip3 install pyTelegramBotAPI==3.7.9
# pip3 install python-telegram-bot==12.7
# pip3 install slick-bitcoinrpc==0.1.4
# pip3 install python-dotenv==0.18.0
# Then setup .env file with required variables
# See https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659 to get TELEGRAM_CHAT_ID
# See https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token to get TELEGRAM_TOKEN

load_dotenv()

HOME = expanduser("~")
CHAIN = "KMD"
RPCPORT = 7771
KMD_CONF = HOME + '/.komodo/komodo.conf'
NN_ADDR = os.getenv('NN_ADDR')
DEST_ADDR = os.getenv('DEST_ADDR')
PUBKEY = os.getenv('NN_PUBKEY')
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

with open(KMD_CONF, 'r') as f:
    for line in f:
        l = line.rstrip()
        if re.search('rpcuser', l):
            rpcuser = l.replace('rpcuser=', '')
        elif re.search('rpcpassword', l):
            rpcpassword = l.replace('rpcpassword=', '')
RPC = Proxy("http://%s:%s@127.0.0.1:%d"%(rpcuser, rpcpassword, int(RPCPORT)))

class RequestsHandler(Handler):
    def emit(self, record):
        log_entry = self.format(record)
        payload = {
            'chat_id': TELEGRAM_CHAT_ID,
            'text': log_entry,
            'parse_mode': 'HTML'
        }
        return requests.post("https://api.telegram.org/bot{token}/sendMessage".format(token=TELEGRAM_TOKEN),
                             data=payload).content
class LogstashFormatter(Formatter):
    def __init__(self):
        super(LogstashFormatter, self).__init__()

    def format(self, record):
        t = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')

        return "<i>{datetime}</i><pre>\n{message}</pre>".format(message=record.msg, datetime=t)

logger = logging.getLogger()
logger.setLevel(logging.WARNING)
handler = RequestsHandler()
formatter = LogstashFormatter()
handler.setFormatter(formatter)
logger.addHandler(handler)


# check if recently mined
min_confs = 99999
txinfo = RPC.listtransactions("", 777)
for tx in txinfo:
    if tx['category'] == 'immature':
        min_confs = tx['rawconfirmations']
if min_confs > 120 and min_confs != 99999:
    logger.warning(f"You have not mined for {min_confs} blocks!")

# Check and clear balance
balance = RPC.getbalance()
if balance > 150:
    send_amount = balance - 50
    txid = RPC.sendtoaddress(DEST_ADDR, send_amount)
    logger.warning(f"{send_amount} {CHAIN} sent to {DEST_ADDR}. TXID: {txid}")
    txid = RPC.sendtoaddress(NN_ADDR, 40)
    logger.warning(f"40 {CHAIN} sent to {NN_ADDR}. TXID: {txid}")
